#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-Nord}" # Set by `nb` • Mon Apr 25 13:45:28 +03 2022

export NB_AUTO_SYNC="${NB_AUTO_SYNC:-1}" # Set by `nb` • Fri Jul 15 10:43:24 +03 2022

export NB_COLOR_THEME="${NB_COLOR_THEME:-nb}" # Set by `nb` • Thu Nov 24 12:23:12 +03 2022

export NB_ENCRYPTION_TOOL="${NB_ENCRYPTION_TOOL:-gpg}" # Set by `nb` • Thu Nov 24 12:30:52 +03 2022
